### ISSUE TITLE
Getting syntax error when deploying my own schema.prisma

### ISSUE THREAD

**Issue by ameerulislam** [maoosi/prisma-appsync#36] opened 2022-02-02 08:24 UTC
This error only happens when I do it with my own database schema. The sample one works fine.
`yarn deploy   
yarn run v1.22.17
warning package.json: No license field
$ prisma generate && cd cdk && cdk deploy
Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (3.9.0 | library) to ./node_modules/@prisma/client in 833ms

SyntaxError: Syntax Error: Expected Name, found "}". (914:5)
  912 |         
  913 |         
 914 |     }
      |     ^
  915 | 
  916 |     input DbTest3OrderByInput {
  917 |         id: OrderByArg
    at e (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:175469:20)
    at Object.parse (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:176938:19)
    at Object.parse2 [as parse] (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:198238:24)
    at coreFormat (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:199163:18)
    at format2 (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:199348:18)
    at /Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:228996:16
    at Object.format (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:229010:16)
    at PrismaAppSyncCompiler.makeFile (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:322770:42)
    at async PrismaAppSyncCompiler.makeSchema (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:322567:33)
    at async Object.onGenerate (/Users/ameer/Documents/DDLPreDev/Ameer_DDLDevs/Appsyncprisma-prod1/node_modules/prisma-appsync/dist/generator.js:322973:9)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by ameerulislam** [comment] 2022-02-02 12:41
I found the tables that was causing the problem but they seem to be simple tables which are similar to my other tables.

`model db_test3 {
  id                BigInt @default(autoincrement())
  function_name     String @db.VarChar
  frequency         Int?
  function_priority Int?
  customer_priority Int?

  @@id([id, function_name])
}
`

`model devops_resource_priority_tags {
  id                       BigInt @default(autoincrement())
  key                      String @db.VarChar
  value                    String @db.VarChar
  count                    Int?
  tag_priority             Int?
  dev_engineer_priority    Int?
  devops_engineer_priority Int?
  dev_lead_priority        Int?

  @@id([id, key, value])
  @@unique([key, value])
}`

**Comment by maoosi** [comment] 2022-02-05 11:08
Seems like the issue is due to Prisma-AppSync not being able to extract unique fields from the `@@unique` API attribute and therefore not being able to generate the associated GraphQL Schema properly.

I'll add the issue to the roadmap, so it can be resolved in the next release. In the meantime, I can suggest adding `@unique` API attribute on both `id` fields, such as:

```prisma
model db_test3 {
    id      BigInt      @unique @default(autoincrement())
}

model devops_resource_priority_tags {
    id      BigInt      @unique @default(autoincrement())
}
```

It is not perfect, but at least you should be able to generate your GraphQL Schema without errors.

**Closed** 2022-02-07 05:57 UTC
Labels: bug / confirmed

**Comment by ameerulislam** [comment] 2022-02-07 06:42
@unique worked. thanks

**Comment by ameerulislam** [comment] 2022-02-08 06:21
and when I remove and make it 1 primary key and just keep the id as primary key and the other 2 as unique. That also works.
